#!/usr/bin/python3

import rclpy # type: ignore
from rclpy.node import Node # type: ignore
from std_msgs.msg import Char # type: ignore
from geometry_msgs.msg import Pose2D # type: ignore
from random import randint


# Constants
OBSTACLE_LEFT = ord('L')
OBSTACLE_RIGHT = ord('R')
OBSTACLE_NONE = ord('N')


# Start the node
def startNode():
    rclpy.init()
    aNode= Node("navigation")
    emergencyStoper = ROSNavigator(aNode)
    # Start infinite loop
    rclpy.spin(aNode)
    # Clean everything and switch the light off
    aNode.destroy_node()
    rclpy.shutdown()


# Node execution
class ROSNavigator():
    def __init__(self, rosNode):
        # Logger
        self._logger = rosNode.get_logger()
        # Publisher for giving order to the mover
        self._pub_move = rosNode.create_publisher(Pose2D, '/t800/move', 10)
        # Subscriber to the scanner analysis
        self._sub_obstacle = rosNode.create_subscription(Char, '/t800/obstacle', self.obstacle_callback, 10)
        # Variables
        self._forward = True
        self._turnLeft = False
        self._turnRight = False
        self._i = 0
        self._overturn = False
        self._beginOverturn = 0
        self._overturnTime = 0
        # Timer to count every 0.1 second and differ some actions
        self._timer_differer = rosNode.create_timer(0.1, self.differer_callback)
        # Log the start
        self._logger.info('Started !')
        # Publish the first move command
        self.move_publish()

    # Move command publisher, 
    def move_publish(self):
        x, theta = 0.0, 0.0
        # If we have to move forward, we set the linear speed to 1 time the default speed
        if self._forward:
            x = 1.0
        # If we have to turn left, we set the angular speed to 1 positive time the default speed
        if self._turnLeft:
            theta = 1.0
        # If we have to turn right, we set the angular speed to 1 negative time the default speed
        elif self._turnRight:
            theta = -1.0
        # Publish the move command to the topic
        self._pub_move.publish(Pose2D(x=x, theta=theta))

    
    # Obstacle subscriber callback, set the move command according to the obstacle position
    def obstacle_callback(self, char_msg):
        # If the obstacle is on the left, we turn right
        if char_msg.data == OBSTACLE_LEFT and not self._turnLeft:
            self._turnLeft = False
            self._turnRight = True
            self._forward = False
            self._logger.info('Turn to the right')
            # Publish the move command
            self.move_publish()
        # If the obstacle is on the right, we turn left
        elif char_msg.data == OBSTACLE_RIGHT and not self._turnRight:
            self._turnLeft = True
            self._turnRight = False
            self._forward = False
            self._logger.info('Turn to the left')
            # Publish the move command
            self.move_publish()
        # When there is no obstacle, we move over turn a random number and then go forward
        else :
            self._overturn = True
            self._beginOverturn = self._i
            self._overturnTime = randint(3, 10)
            self._logger.info('Begin overturn for a time of ' + str(self._beginOverturn))

    def differer_callback(self) :
        if self._overturn and self._i > self._beginOverturn + self._overturnTime :
            self._logger.info('End overturn')
            self._overturn = False
            self._turnLeft = False
            self._turnRight = False
            self._forward = True
            # Publish the move command
            self.move_publish()
        self._i += 1


# Execute the function.
if __name__ == "__main__":
    startNode()