#!/usr/bin/python3

import rclpy # type: ignore
from rclpy.node import Node # type: ignore
from std_msgs.msg import String # type: ignore
from sensor_msgs.msg import Image # type: ignore
import numpy as np # type: ignore
import cv2
import signal


# Default parameters
DEFAULT_xxx= 30

'''
# Global flag to handle Ctrl-C interruption
isOk = True

# Function to handle Ctrl-C interrupt
def signalInteruption(signum, frame):
    global isOk
    print("\nCtrl-c pressed")
    isOk = False

# Handle Ctrl-C interruption by running the signalInteruption function
signal.signal(signal.SIGINT, signalInteruption)
'''


# Start the node
def startNode():
    rclpy.init()
    aNode= Node("slam")
    slam = ROSSlam(aNode)
    # Initialize ROS node and slam
    camera.initializeROSNode()

    '''
    # Start infinite loop
    while isOk:
        slam.image_acquisition()
        slam.publish_imgs()
        rclpy.spin_once(aNode, timeout_sec=0.001)
    '''

    # Clean end
    slam.disconnect()
    aNode.destroy_node()
    rclpy.shutdown()

'''
# Node execution
class ROSSlam():
    def __init__(self, rosNode):
        # Logger
        self._logger = rosNode.get_logger()
        # Publisher for detection message
        self._pub_detection = rosNode.create_publisher(String, '/t800/detection', 10)
        # Publisher for camera images
        self._pub_color_image = rosNode.create_publisher(Image, '/t800/color_image', 10)
        self._pub_depth_colormap = rosNode.create_publisher(Image, '/t800/depth_colormap', 10)
        # Parameters
        rosNode.declare_parameter('fps', DEFAULT_FPS)
        rosNode.declare_parameter('pixel_detection_treshold', DEFAULT_PIXEL_DETECTION_TRESHOLD)
        rosNode.declare_parameter('lower_hue', DEFAULT_LOWER_HUE)
        rosNode.declare_parameter('upper_hue', DEFAULT_UPPER_HUE)
        rosNode.declare_parameter('lower_saturation', DEFAULT_LOWER_SATURATION)
        rosNode.declare_parameter('lower_value', DEFAULT_LOWER_VALUE)
        # Constants
        self._fps = rosNode.get_parameter('fps').value
        self._pixel_detection_treshold = rosNode.get_parameter('pixel_detection_treshold').value
        self._lower_hue = rosNode.get_parameter('lower_hue').value
        self._upper_hue = rosNode.get_parameter('upper_hue').value
        self._lower_saturation = rosNode.get_parameter('lower_saturation').value
        self._lower_value = rosNode.get_parameter('lower_value').value
        self._pipeline = rs.pipeline()
        self._config = rs.config()
        # Variables
        self._color_frame = None
        self._depth_frame = None
        self._color_image = None
        self._depth_image = None
        # Log the start
        self._logger.info('Started !')
    
    # Function to start the initialization of the camera and begin the image aquisition
    def initializeROSNode(self):
        # Initialisation of the camera
        self._init_camera()
    
    # Function to imitialize the camera
    def _init_camera(self):
        # Configure the camera for color
        self._config.enable_stream(rs.stream.color, 848, 480, rs.format.bgr8, self._fps)
        self._config.enable_stream(rs.stream.depth, 848, 480, rs.format.z16, self._fps)
        # Start of pipeline
        self._pipeline.start(self._config)
        self._logger.info('Camera initialized !')
    
    def disconnect(self):
        # Stop the streaming and disconnect the camera
        self._pipeline.stop()
        self._logger.info('Camera disconected !')
    
    # Function to aquire the images from the camera by reading the frames and start the object detection
    def image_acquisition(self):
        # Read the images
        self.read_imgs()
        # Start the object detection
        if self._color_image is not None:
            self.detect_object()
    
    # Function to read the images from the camera
    def read_imgs(self):
        # Wait for the next frames from the camera and get the color image
        frames = self._pipeline.wait_for_frames()
        self._color_frame = frames.get_color_frame()
        self._depth_frame = frames.get_depth_frame()
        # If the color frame is not empty, convert it to a numpy array
        if not (self._color_frame and self._depth_frame):
            self._color_image = None
            self._depth_image = None
            self._depth_colormap = None
        else :
            self._color_image = np.asanyarray(self._color_frame.get_data())
            self._depth_image = np.asanyarray(self._depth_frame.get_data())
            # Apply a colormap to the depth image
            self._depth_colormap = cv2.applyColorMap(cv2.convertScaleAbs(self._depth_image, alpha=0.03), cv2.COLORMAP_JET)

    # Function to publish the images on the ROS topics
    def publish_imgs(self):
        if self._color_image is not None and self._depth_colormap is not None:
            # Image conversion
            color_msg = self._convert_to_ros_img(self._color_image)
            depth_msg = self._convert_to_ros_img(self._depth_colormap)
            # Publish the images
            self._pub_color_image.publish(color_msg)
            self._pub_depth_colormap.publish(depth_msg)
            
    def _convert_to_ros_img(self, cv_img):
        # Conversion d'une image OpenCV en message Image de ROS
        msg = Image()
        msg.header.stamp = rclpy.time.Time().to_msg()
        msg.height = cv_img.shape[0]
        msg.width = cv_img.shape[1]
        msg.encoding = "bgr8"  # Encodage pour l'image couleur
        msg.data = np.array(cv_img).tobytes()
        return msg

    # Function to detect the object in the image
    def detect_object(self):
        # Convert the color image to HSV so that we can apply on the HSV, which is easier than on RGB
        hsv_image = cv2.cvtColor(self._color_image, cv2.COLOR_BGR2HSV)
        # Define the range of color in HSV
        lower_range = np.array([self._lower_hue, self._lower_saturation, self._lower_value])
        upper_range = np.array([self._upper_hue, 255, 255])
        # Create a mask with all the pixels that are in the color range
        mask = cv2.inRange(hsv_image, lower_range, upper_range)
        # Count the number of white pixels in the mask
        white_pixels = cv2.countNonZero(mask)
        # If enough white pixels are detected, publish a message
        if white_pixels > self._pixel_detection_treshold:
            self._pub_detection.publish(String(data="Phantom detected !"))
            self._logger.info('Phantom detected ! -> Published on dedicated topic.')

'''
# Execute the function.
if __name__ == "__main__":
    startNode()