#!/usr/bin/python3
import rclpy
from rclpy.node import Node
from geometry_msgs.msg import Twist

print("test_move :: START...")

def infiniteMove():
    # Initialize ROS node with ROS client
    rclpy.init()
    aNode= Node( "infMover" )
    mover= ROSMover(aNode)
    # Start infinite loop
    rclpy.spin(aNode)
    # Clean everything and switch the light off
    aNode.destroy_node()
    rclpy.shutdown()

class ROSMover: 
    def __init__(self, rosNode):
        self._publisher= rosNode.create_publisher( Twist, '/multi/cmd_nav', 10 )
        self._timer = rosNode.create_timer(0.5, self.timer_callback)
        self._i = 0

    def timer_callback(self):
        velocity = Twist()
        # Feed Twist velocity values
        velocity.linear.x = -0.3
        velocity.angular.z = 0.0
        if self._i%5 == 0:
            velocity.angular.z = 1.0
            velocity.linear.x = 0.0
        # Publish 
        self._publisher.publish(velocity)
        # Increment
        self._i += 1

# Execute the function.
if __name__ == "__main__":
    infiniteMove()